### ISSUE TITLE
ESX Bug

### ISSUE THREAD

**Issue by FilipeCuco** [renzuzu/renzu_multicharacter#4] opened 2022-11-29 01:14 UTC
in esx when I try to create a character it spams the console with this:

![image](https://user-images.githubusercontent.com/116587926/204414180-79e2dd43-6284-4e0a-aee7-7c745f271c7a.png)

and then it goes like this:
![image](https://user-images.githubusercontent.com/116587926/204414286-3bfcfa6d-3184-409d-ac9e-77e1d7ff3e6b.png)

**Comment by renzuzu** [comment] 2022-11-29 01:37
are you able to repeat this? what esx version?

**Comment by FilipeCuco** [comment] 2022-11-29 01:43
I am using the most updated one

**Comment by FilipeCuco** [comment] 2022-11-29 01:44
I have to remove esx_identity and esx_multicharacter correct?

**Comment by renzuzu** [comment] 2022-11-29 01:45
yes you should remove both.

tell if the issue is repeatable..

that issue means the character is not registered successfully

**Comment by FilipeCuco** [comment] 2022-11-29 01:51
everything is correct and it is not working

**Comment by renzuzu** [comment] 2022-11-29 01:54
try removing the print 
from server/framework/main.lua
replace with this

```
LoadPlayer = function(source)
	while not GetPlayerFromId(source) do Wait(0) end
	local ply = Player(source).state
	ply:set('identifier',GetPlayerFromId(source).identifier,true)
	return true
end
```

and check any server error. 

i use latest esx legacy too, and i just recently installed from friends a while ago, its a drag and drop.
possible issue in your end.
if you want this to be solved show me console server .logs

**Comment by renzuzu** [comment] 2022-11-29 01:57
also tell me if its repeatable.
if yes restart your server, we experience this in past, if we load a lot of tons vehicle assets before loading esx or oxmysql
the esx throw an error while starting up. 

or you could try /relog (if resource is not restarted) and try to register again.

**Comment by renzuzu** [comment] 2022-11-29 02:48
i was able to replicate your issue, exactly the same .

there should be an error from server console.
i dont know if your video shows the updated console. sometimes console is not updating, you have to enter or something. just a hunch.

in my case when newly install esx, no esx identiy sql it throw an error for firstname and lastname.

if you could provide more viable info.
else this is not actionable as its fully working on me and my other server using tesx legacy latest.

i will investigate your issue what its causing.

**Comment by renzuzu** [comment] 2022-11-29 03:23
100% problem in your end, make sure you install ESX properly.
as in your video there is no users. its probably a newly installed

dont forget to install esx identity SQL, and ESX skin SQL

im closing as this is not actionable and not a bug

**Closed by renzuzu** 2022-11-29 03:23 UTC

**Comment by beastinrapper** [comment] 2022-11-29 21:09
I'm having the same issues, first time ever using Multi Characters in my server but my server is 10months old so I have previous logged identifiers in my SQL from players so I know my esx_identifiers has been installed into my database correctly. Im thinking it has something to do with my users table but even after reinstalling the table from Es_essentials and then using your provided SQL input, still having this issue.

**Comment by beastinrapper** [comment] 2022-11-29 22:06
Fixed it....

Drop your `users` Database and add this in your sql

CREATE TABLE `users` (
	`identifier` VARCHAR(60) NOT NULL,
	`accounts` LONGTEXT NULL DEFAULT NULL,
	`group` VARCHAR(50) NULL DEFAULT 'user',
	`inventory` LONGTEXT NULL DEFAULT NULL,
	`job` VARCHAR(20) NULL DEFAULT 'unemployed',
	`job_grade` INT NULL DEFAULT 0,
	`loadout` LONGTEXT NULL DEFAULT NULL,
	`position` VARCHAR(255) NULL DEFAULT '{"x":-269.4,"y":-955.3,"z":31.2,"heading":205.8}',

	PRIMARY KEY (`identifier`)
) ENGINE=InnoDB;



 Then add the esx_skin .sql and the @ esx_identity sql that renzu provided

**Comment by beastinrapper** [comment] 2022-11-29 22:37
For those running into this issue who already have previous player information in the `users` database query with character single or multiple, In front of the identifiers in the identifier tab you should be able to just add "char1:" (Without quotes) "char2:" (so on and so forth but if you are not converting over from another multi character system and your users only have one character then dont worry about char2, it will create char2 when that identifier makes a new character in slot 2)   

so all of your identifiers in your data base should now look like

            char1:ec45676414165456456HI123154
            
Hope this helps
